### ISSUE TITLE
Error: Request cancelled. panic: runtime error: index out of range [24] with length 16

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/substrate-client#24]
recently I start to see this error while using Terraform plugin, with repeated trying it would eventually work.
I was going to open this issue in the plugin repo but @OmarElawady point out that this is related to the substrate client.

feel free to transfer it where you think it is most relevant.

**logs**

```sh
grid_network.ownnet: Creating...
grid_network.ownnet: Still creating... [10s elapsed]
╷
│ Error: Request cancelled
│ 
│   with grid_network.ownnet,
│   on main.tf line 59, in resource "grid_network" "ownnet":
│   59: resource "grid_network" "ownnet" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-grid_v0.1.27 plugin:

panic: runtime error: index out of range [24] with length 16

goroutine 65 [running]:
github.com/threefoldtech/substrate-client.(*Substrate).checkForError(0xc0002927b0, 0xc00027fba8, 0x2c, {0x4c, 0x66, 0x1e, 0xb4, 0x8, 0x63, 0x94, ...}, ...)
	github.com/threefoldtech/substrate-client@v0.0.0-20220328075445-99d0ff259160/utils.go:237 +0x3dd
github.com/threefoldtech/substrate-client.(*Substrate).CreateNodeContract(0xc000149c08, {0xf885d0, 0xc000204b00}, 0x0, {0x0, 0x0, 0x0}, {0xc00053c560, 0x20}, 0x0)
	github.com/threefoldtech/substrate-client@v0.0.0-20220328075445-99d0ff259160/contract.go:184 +0x2c7
github.com/threefoldtech/terraform-provider-grid/internal/provider.deployConsistentDeployments({0xf7c3e8, 0xc00049aa80}, 0xc000472460, 0xf82200, 0xc0001b0a00, {0xf66ca0, 0xc000149e30}, 0xc000295400)
	github.com/threefoldtech/terraform-provider-grid/internal/provider/common.go:402 +0x7eb
github.com/threefoldtech/terraform-provider-grid/internal/provider.deployDeployments({0xf7c3e8, 0xc00049aa80}, 0x0, 0x0, 0xf66ca0, {0xf66ca0, 0xc000149e30}, 0xc000295400, 0x1)
	github.com/threefoldtech/terraform-provider-grid/internal/provider/common.go:334 +0x10b
github.com/threefoldtech/terraform-provider-grid/internal/provider.(*NetworkDeployer).Deploy(0xc00027d4b8, {0xf7c3e8, 0xc00049aa80}, 0xe)
	github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_network.go:638 +0xb9
github.com/threefoldtech/terraform-provider-grid/internal/provider.resourceNetworkCreate({0xf7c3e8, 0xc00049aa80}, 0xc0004f76c0, {0xcbd040, 0xc000295400})
	github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_network.go:681 +0x4f0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00029aee0, {0xf7c378, 0xc0005fa4c0}, 0x2, {0xcbd040, 0xc000295400})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:341 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00029aee0, {0xf7c378, 0xc0005fa4c0}, 0xc000222750, 0xc0004b7000, {0xcbd040, 0xc000295400})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0002927c8, {0xf7c378, 0xc0005fa4c0}, 0xc00007e460)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000294c00, {0xf7c420, 0xc000188180}, 0xc00022c070)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xe023a0, 0xc000294c00}, {0xf7c420, 0xc000188180}, 0xc00049a0c0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002ac700, {0xf8b9d0, 0xc0000f8180}, 0xc000492000, 0xc0004419e0, 0x15c9ac0, 0x0)
	google.golang.org/grpc@v1.41.0/server.go:1279 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0002ac700, {0xf8b9d0, 0xc0000f8180}, 0xc000492000, 0x0)
	google.golang.org/grpc@v1.41.0/server.go:1608 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.41.0/server.go:923 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.41.0/server.go:921 +0x294

Error: The terraform-provider-grid_v0.1.27 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**TF configuration file**
```
terraform {
  required_providers {
    grid = {
      source = "threefoldtech/grid"
    }
  }
}

provider "grid" {
}

variable "user" {
  type = string
  default = "test"
}


resource "random_string" "random" {
  length           = 3
  special          = false
  upper            = false
}

resource "random_password" "password" {
  length           = 8
  special          = true
}

locals {
  password = "${random_password.password.result}"
  user     = "${var.user}"
  admin_name = "${var.user}"
  server_req = "oc_server_req"
  name_req = "oc_name_req"
  network_name = "oc_network_${var.user}_${random_string.random.result}"
  disk_name = "oc_disk"
  vm_name = "oc_vm"
  disk_size = 70 #GB
  rootfs_size = 2 #GB
  disk_mount_point = "/var/lib/docker"
  vm_cpu = 2
  vm_memory = 8096
  domain_name = "owncloud${var.user}${random_string.random.result}"
}
resource "grid_scheduler" "sched" {
  requests {
    name = local.server_req
    cru = local.vm_cpu
    sru = local.disk_size + local.rootfs_size
    mru = local.vm_memory
  }

  requests {
    name = local.name_req
    domain = true
  }
}

resource "grid_network" "ownnet" {
  nodes = [grid_scheduler.sched.nodes[local.server_req]]
  ip_range      = "10.1.0.0/16"
  name          = local.network_name
  description   = "server network"
  add_wg_access = true
}

resource "grid_deployment" "nodes" {
  node = grid_scheduler.sched.nodes[local.server_req]
  network_name = grid_network.ownnet.name
  ip_range     = lookup(grid_network.ownnet.nodes_ip_range, grid_scheduler.sched.nodes[local.server_req], "")
  disks {
    name        = local.disk_name
    # will hold images, volumes etc. modify the size according to your needs
    size        = local.disk_size
    description = "volume holding docker data"
  }
  vms {
    name        = "owncloud_${var.user}"
    flist       = "https://hub.grid.tf/samehabouelsaad.3bot/abouelsaad-owncloud-10.9.1.flist"
    entrypoint  = "/sbin/zinit init"
    cpu         = local.vm_cpu
    memory      = local.vm_memory
    rootfs_size  = local.rootfs_size * 1024
    mounts {
      disk_name   = local.disk_name
      mount_point = local.disk_mount_point
    }
    env_vars = {
      SSH_KEY     = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSkhNAIP22RH/sQx7alFS6vcqw1OAQUkC5MLv6t3L78YVTRv+/owSqIqCQHr2+zfb3aJijsxj9nqg54rVkEiCXOkT6IE/MGWSP6O/x/cCG8J7AT+OCCjo9IB/+V3CA8yREHi7ggqPv6hEfNoa1AMbnxqxT7a+5sJUVd14/Ib9OQKWBCXzosa0SjTY/RO1SrL93E80N+SJQRBCMemzlepn4wLDWvqs7DiruY+g9E2CskhDijt4iJCuNFZzAcTS3UeqxOG2QfLK2zc8M9/AycMcEyHn94Lml6V75Lk09iLB9QGTGsa4oAD3GFLce4VoKKZx0e6lwwnMNoAHKhBEMFmO5 root@waleed-ng",
      OWNCLOUD_DOMAIN = data.grid_gateway_domain.domain.fqdn,
      OWNCLOUD_ADMIN_USERNAME = local.admin_name,
      OWNCLOUD_ADMIN_PASSWORD = local.password,
      # configure smtp settings bellow only If you have an working smtp service and you know what you’re doing.
      # otherwise leave these settings empty. gives wrong smtp settings will cause issues/server errors in taiga.
      OWNCLOUD_MAIL_SMTP_SECURE = "none", # tls, ssl, or none
      OWNCLOUD_MAIL_SMTP_HOST = "",
      OWNCLOUD_MAIL_SMTP_NAME = "",
      OWNCLOUD_MAIL_SMTP_PASSWORD = "",
      OWNCLOUD_MAIL_SMTP_PORT = "",
      OWNCLOUD_MAIL_DOMAIN =  data.grid_gateway_domain.domain.fqdn,
      OWNCLOUD_MAIL_FROM_ADDRESS = "owncloud",
    }
    planetary = true
  }
}

data "grid_gateway_domain" "domain" {
  node = grid_scheduler.sched.nodes[local.name_req]
  name = local.domain_name
}
resource "grid_name_proxy" "p1" {
  node            = grid_scheduler.sched.nodes[local.name_req]
  name            = local.domain_name # this is not the domain name, it is resource name, no?
  backends = [format("http://%s:80", grid_deployment.nodes.vms[0].ygg_ip)]
  tls_passthrough = false
}


output "node_ip" {
  value = grid_deployment.nodes.vms[0].ip
}


output "node_ygg_ip" {
  value = grid_deployment.nodes.vms[0].ygg_ip
}

output "admin_name" {
  value = local.admin_name
}

output "admin_password" {
  sensitive = true
  value = local.password
}

output "fqdn" {
  value = data.grid_gateway_domain.domain.fqdn
}
```

**plugin version:**
v0.1.27

**Comment by OmarElawady** [comment]
Terraform scheduler was picking a rented node, and substrate client didn't have this error code, both are added in v0.1.29.
